### ISSUE TITLE
 Chapter02 : H2 database setting

### ISSUE THREAD

**Issue by s-w-choi** [sungwon-097/Spring-Boot-JWT-Tutorial#2]
USER는 예약어이기 때문에 USER 테이블을 생성하려고 하면 충돌이 생김.

```
// application.yml
spring: 
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
```
